### ISSUE TITLE
与SlowQuitApps同时使用会带来奇怪的后果

### ISSUE THREAD

**Issue by Kainichy** [lihaoyun6/capXDR-plugins#1]
First issue!
在使用您的capXDR程序同时，运行[SlowQuitApps](https://github.com/dteoh/SlowQuitApps)会导致在退出程序时意外进行截图。

**Comment by lihaoyun6** [comment]
请更新到v0.1.13以上的版本(最新v0.1.16), 并重新设置快捷键(一定要重新设置一次)
旧版本中对于快捷键event里flags部分的读取行为没有进行验证. 可能会误读"非法"快捷键, 导致快捷键识别出现错误.
您遇到的问题可能是由于这个bug所产生的. 如果在更新并重设快捷键之后依旧没有解决, 请继续回复此issue, 我将持续关注.
如果解决了, 也请回复此消息, 以便提醒我关闭此issue

**Comment by lihaoyun6** [comment]
问题已在最新的v0.1.17中修复了
